### ISSUE TITLE
Is it possible to display more information about the Jira Ticket in the MSM pop up window

### ISSUE THREAD

**Issue by marvalalex** [MarvalSoftware/MarvalSoftware.JIRA#1]
As an MSM service management user I will know little or nothing about Jira. I may not even have a log in to Jira to drill down into Jira Tickets associated with MSM. 
Can the information displayed about the Jira ticket be expanded - Even the description gets truncated.
As a service management user of MSM I'd probably need to know - the issue description - it's status - estimated completion date - its priority.

**Comment by CodeBush91** [comment]
Hi Alex,

Thank you for your comments, out of the box JIRA allows view access without the need to authenticate. Once a JIRA issue is linked in MSM you will be able to click the link and be taken directly to the JIRA issue where you will have access to all the information.
